//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int Id { get; set; }
        public string CompanyGuid { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> LangId { get; set; }
        public string Content { get; set; }
        public Nullable<bool> AnswerType { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<bool> IsPassive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
