//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionPath
    {
        public int Id { get; set; }
        public Nullable<int> CustomerAnswersId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public string CustomerGuid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsPassive { get; set; }
    
        public virtual CustomerAnswers CustomerAnswers { get; set; }
    }
}
