//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Questionnaire.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUsers
    {
        public int Id { get; set; }
        public string CompanyGuid { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> JobStartDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public bool SuperAdmin { get; set; }
        public Nullable<bool> IsPassive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
